<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Examples.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# Examples: Interactive visualisation in Python 



In this train, we will focus on creating unique and interactive visualisations. We will learn how to make our code block outputs interactive for the end user.

> ⚠️ **Note:** An active internet connection is needed to complete the exercises within this notebook. 

> ⚠️ **Note:** This exercise works best when executed in a Jupyter notebook.

## Learning objectives
By the end of this train, you should be able to:
* Create advanced custom visualisations in Python.
* Create interactive visualisations in a Jupyter notebook.

## Introduction

Sometimes we require interaction in our Jupyter notebooks rather than a PowerBI dashboard. A potential reason would be to employ more sophisticated technology to meet typical business intelligence use cases. Traditional BI tools are ideal for creating dashboards created from SQL or CSV data. However, when we try to display information created by more sophisticated logic, we often fall short.

With interactive widgets in a notebook, we can leverage the full power of Python to express calculations and build visualisations while exposing "our logic" to the end user, allowing them to modify aspects of the visualisation. We may either add a few interactive controls and plots to notebooks or build completely functional applications and interactive dashboards. Both can be created with components from the built-in core widgets, such as `buttons`, `sliders`, and `dropdowns`, or with the rich ecosystem of custom widget libraries based on the Jupyter widgets framework, such as interactive maps with `ipyleaflet` or `2-D plots` with `bqplot`.

## Getting the notebook ready
Let's ensure we have the relevant packages installed.

### Step 1: Install the relevant packages

In [1]:
pip install scipy

Collecting scipyNote: you may need to restart the kernel to use updated packages.

WARNING: Error parsing dependencies of certifi: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\envs\\sqlenv\\lib\\site-packages\\certifi-2025.10.5.dist-info\\METADATA'

  Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: numpy<2.5,>=1.23.5 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from scipy) (2.2.5)
Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.3 MB ? eta -:--:--
    --------------------------------------- 0.5/41.3 MB 558.9 kB/s eta 0:01:13
    --------------------------------------- 0.5/41.3 MB 558.9 kB/s eta 0:01:13
    --------------------------------------- 0.8/41.3 MB 621.2 kB/s eta 0:01:06
    --------------------------------------- 0.8/41.3 MB 621.2 kB/s eta 0:01:06
   - -------------------------------------- 1.0/41.3 MB 621.2 kB/s eta 0:01:05
   - -------------------------------------- 1.0/41.3 MB 621.2 kB/s eta 0:01:05
   - -------------------------------------- 1.3/41.3 MB 593.8 kB/s eta 0:01:08
   - -------------------------------------- 1.3/41.3 MB 593.8 kB/s eta 0:01:08
   - -------------------------------------- 1.6/41.3 MB 603.5 kB/s eta 0:01:06
   - -------------------------------------- 1.6/41.3 MB 603.5 kB/s eta 0:01:06
   - -------------------------------------- 1.8/41.3 MB 599.2 kB/s eta 0:01:06
   - -------------------------------------- 1.8/41.3 MB 599.2 kB/s eta 0:01:06
   -- ------------------------------------- 2.1/41.3 MB 602.2 kB/s eta 0:01:06
   -- ------------------------------------- 2.1/41.3 MB 602.2 kB/s eta 0:01:06
   -- ------------------------------------- 2.4/41.3 MB 599.2 kB/s eta 0:01:05
   -- ------------------------------------- 2.4/41.3 MB 599.2 kB/s eta 0:01:05
   -- ------------------------------------- 2.6/41.3 MB 599.1 kB/s eta 0:01:05
   -- ------------------------------------- 2.6/41.3 MB 599.1 kB/s eta 0:01:05
   -- ------------------------------------- 2.9/41.3 MB 595.0 kB/s eta 0:01:05
   -- ------------------------------------- 2.9/41.3 MB 595.0 kB/s eta 0:01:05
   -- ------------------------------------- 2.9/41.3 MB 595.0 kB/s eta 0:01:05
   --- ------------------------------------ 3.1/41.3 MB 593.3 kB/s eta 0:01:05
   --- ------------------------------------ 3.1/41.3 MB 593.3 kB/s eta 0:01:05
   --- ------------------------------------ 3.4/41.3 MB 595.7 kB/s eta 0:01:04
   --- ------------------------------------ 3.4/41.3 MB 595.7 kB/s eta 0:01:04
   --- ------------------------------------ 3.7/41.3 MB 589.5 kB/s eta 0:01:04
   --- ------------------------------------ 3.7/41.3 MB 589.5 kB/s eta 0:01:04
   --- ------------------------------------ 3.9/41.3 MB 590.1 kB/s eta 0:01:04
   --- ------------------------------------ 3.9/41.3 MB 590.1 kB/s eta 0:01:04
   ---- ----------------------------------- 4.2/41.3 MB 587.9 kB/s eta 0:01:04
   ---- ----------------------------------- 4.2/41.3 MB 587.9 kB/s eta 0:01:04
   ---- ----------------------------------- 4.5/41.3 MB 586.1 kB/s eta 0:01:03
   ---- ----------------------------------- 4.5/41.3 MB 586.1 kB/s eta 0:01:03
   ---- ----------------------------------- 4.7/41.3 MB 588.1 kB/s eta 0:01:03
   ---- ----------------------------------- 4.7/41.3 MB 588.1 kB/s eta 0:01:03
   ---- ----------------------------------- 5.0/41.3 MB 588.6 kB/s eta 0:01:02
   ---- ----------------------------------- 5.0/41.3 MB 588.6 kB/s eta 0:01:02
   ----- ---------------------------------- 5.2/41.3 MB 584.9 kB/s eta 0:01:02
   ----- ---------------------------------- 5.2/41.3 MB 584.9 kB/s eta 0:01:02
   ----- ---------------------------------- 5.5/41.3 MB 588.7 kB/s eta 0:01:01
   ----- ---------------------------------- 5.5/41.3 MB 588.7 kB/s eta 0:01:01
   ----- ---------------------------------- 5.8/41.3 MB 589.1 kB/s eta 0:01:01
   ----- ---------------------------------- 5.8/41.3 MB 589.1 kB/s eta 0:01:01
   ----- ---------------------------------- 6.0/41.3 MB 589.6 kB/s eta 0:01:00
   ----- ---------------------------------- 6.0/41.3 MB 589.6 kB/s eta 0:01:00
   ------ --------------------------------- 6.3/41.3 MB 589.1 kB/s eta 0:01:00
   ------ --------------------------------- 6.3/41.3 MB 589.1 kB/s eta 0:01:00
   ------ --------------------------------- 6.6/41.3 MB 588.6 kB/s eta 0:00:59
   ------ --------------------------------- 6.6/41.3 MB 588.6 kB/s eta 0:00:59
   ------ --------------------------------- 6.8/41.3 MB 589.9 kB/s eta 0:00:59
   ------ --------------------------------- 6.8/41.3 MB 589.9 kB/s eta 0:00:59
   ------ --------------------------------- 7.1/41.3 MB 589.4 kB/s eta 0:00:58
   ------ --------------------------------- 7.1/41.3 MB 589.4 kB/s eta 0:00:58
   ------- -------------------------------- 7.3/41.3 MB 589.8 kB/s eta 0:00:58
   ------- -------------------------------- 7.3/41.3 MB 589.8 kB/s eta 0:00:58
   ------- -------------------------------- 7.6/41.3 MB 588.7 kB/s eta 0:00:58
   ------- -------------------------------- 7.6/41.3 MB 588.7 kB/s eta 0:00:58
   ------- -------------------------------- 7.9/41.3 MB 589.0 kB/s eta 0:00:57
   ------- -------------------------------- 7.9/41.3 MB 589.0 kB/s eta 0:00:57
   ------- -------------------------------- 8.1/41.3 MB 588.6 kB/s eta 0:00:57
   ------- -------------------------------- 8.1/41.3 MB 588.6 kB/s eta 0:00:57
   ------- -------------------------------- 8.1/41.3 MB 588.6 kB/s eta 0:00:57
   -------- ------------------------------- 8.4/41.3 MB 588.3 kB/s eta 0:00:56
   -------- ------------------------------- 8.4/41.3 MB 588.3 kB/s eta 0:00:56
   -------- ------------------------------- 8.7/41.3 MB 587.4 kB/s eta 0:00:56
   -------- ------------------------------- 8.7/41.3 MB 587.4 kB/s eta 0:00:56
   -------- ------------------------------- 8.9/41.3 MB 588.4 kB/s eta 0:00:55
   -------- ------------------------------- 8.9/41.3 MB 588.4 kB/s eta 0:00:55
   -------- ------------------------------- 9.2/41.3 MB 588.1 kB/s eta 0:00:55
   -------- ------------------------------- 9.2/41.3 MB 588.1 kB/s eta 0:00:55
   --------- ------------------------------ 9.4/41.3 MB 587.8 kB/s eta 0:00:55
   --------- ------------------------------ 9.4/41.3 MB 587.8 kB/s eta 0:00:55
   --------- ------------------------------ 9.7/41.3 MB 588.1 kB/s eta 0:00:54
   --------- ------------------------------ 9.7/41.3 MB 588.1 kB/s eta 0:00:54
   --------- ------------------------------ 10.0/41.3 MB 587.8 kB/s eta 0:00:54
   --------- ------------------------------ 10.0/41.3 MB 587.8 kB/s eta 0:00:54
   --------- ------------------------------ 10.2/41.3 MB 587.0 kB/s eta 0:00:53
   --------- ------------------------------ 10.2/41.3 MB 587.0 kB/s eta 0:00:53
   ---------- ----------------------------- 10.5/41.3 MB 587.9 kB/s eta 0:00:53
   ---------- ----------------------------- 10.5/41.3 MB 587.9 kB/s eta 0:00:53
   ---------- ----------------------------- 10.7/41.3 MB 587.1 kB/s eta 0:00:52
   ---------- ----------------------------- 10.7/41.3 MB 587.1 kB/s eta 0:00:52
   ---------- ----------------------------- 11.0/41.3 MB 587.4 kB/s eta 0:00:52
   ---------- ----------------------------- 11.0/41.3 MB 587.4 kB/s eta 0:00:52
   ---------- ----------------------------- 11.3/41.3 MB 587.2 kB/s eta 0:00:52
   ---------- ----------------------------- 11.3/41.3 MB 587.2 kB/s eta 0:00:52
   ----------- ---------------------------- 11.5/41.3 MB 587.5 kB/s eta 0:00:51
   ----------- ---------------------------- 11.5/41.3 MB 587.5 kB/s eta 0:00:51
   ----------- ---------------------------- 11.8/41.3 MB 586.8 kB/s eta 0:00:51
   ----------- ---------------------------- 11.8/41.3 MB 586.8 kB/s eta 0:00:51
   ----------- ---------------------------- 12.1/41.3 MB 586.6 kB/s eta 0:00:50
   ----------- ---------------------------- 12.1/41.3 MB 586.6 kB/s eta 0:00:50
   ----------- ---------------------------- 12.3/41.3 MB 587.8 kB/s eta 0:00:50
   ----------- ---------------------------- 12.3/41.3 MB 587.8 kB/s eta 0:00:50
   ------------ --------------------------- 12.6/41.3 MB 587.6 kB/s eta 0:00:49
   ------------ --------------------------- 12.6/41.3 MB 587.6 kB/s eta 0:00:49
   ------------ --------------------------- 12.8/41.3 MB 587.4 kB/s eta 0:00:49
   ------------ --------------------------- 12.8/41.3 MB 587.4 kB/s eta 0:00:49
   ------------ --------------------------- 13.1/41.3 MB 587.2 kB/s eta 0:00:48
   ------------ --------------------------- 13.1/41.3 MB 587.2 kB/s eta 0:00:48
   ------------ --------------------------- 13.4/41.3 MB 587.0 kB/s eta 0:00:48
   ------------ --------------------------- 13.4/41.3 MB 587.0 kB/s eta 0:00:48
   ------------- -------------------------- 13.6/41.3 MB 586.9 kB/s eta 0:00:48
   ------------- -------------------------- 13.6/41.3 MB 586.9 kB/s eta 0:00:48
   ------------- -------------------------- 13.9/41.3 MB 587.5 kB/s eta 0:00:47
   ------------- -------------------------- 13.9/41.3 MB 587.5 kB/s eta 0:00:47
   ------------- -------------------------- 14.2/41.3 MB 587.3 kB/s eta 0:00:47
   ------------- -------------------------- 14.2/41.3 MB 587.3 kB/s eta 0:00:47
   ------------- -------------------------- 14.4/41.3 MB 587.1 kB/s eta 0:00:46
   ------------- -------------------------- 14.4/41.3 MB 587.1 kB/s eta 0:00:46
   -------------- ------------------------- 14.7/41.3 MB 587.7 kB/s eta 0:00:46
   -------------- ------------------------- 14.7/41.3 MB 587.7 kB/s eta 0:00:46
   -------------- ------------------------- 14.7/41.3 MB 587.7 kB/s eta 0:00:46
   -------------- ------------------------- 14.9/41.3 MB 586.1 kB/s eta 0:00:45
   -------------- ------------------------- 15.2/41.3 MB 586.7 kB/s eta 0:00:45
   -------------- ------------------------- 15.2/41.3 MB 586.7 kB/s eta 0:00:45
   -------------- ------------------------- 15.5/41.3 MB 587.2 kB/s eta 0:00:44
   -------------- ------------------------- 15.5/41.3 MB 587.2 kB/s eta 0:00:44
   -------------- ------------------------- 15.5/41.3 MB 587.2 kB/s eta 0:00:44
   --------------- ------------------------ 15.7/41.3 MB 587.5 kB/s eta 0:00:44
   --------------- ------------------------ 15.7/41.3 MB 587.5 kB/s eta 0:00:44
   --------------- ------------------------ 16.0/41.3 MB 587.3 kB/s eta 0:00:44
   --------------- ------------------------ 16.0/41.3 MB 587.3 kB/s eta 0:00:44
   --------------- ------------------------ 16.3/41.3 MB 587.5 kB/s eta 0:00:43
   --------------- ------------------------ 16.3/41.3 MB 587.5 kB/s eta 0:00:43
   ---------------- ----------------------- 16.5/41.3 MB 587.7 kB/s eta 0:00:43
   ---------------- ----------------------- 16.5/41.3 MB 587.7 kB/s eta 0:00:43
   ---------------- ----------------------- 16.8/41.3 MB 587.5 kB/s eta 0:00:42
   ---------------- ----------------------- 16.8/41.3 MB 587.5 kB/s eta 0:00:42
   ---------------- ----------------------- 17.0/41.3 MB 587.4 kB/s eta 0:00:42
   ---------------- ----------------------- 17.0/41.3 MB 587.4 kB/s eta 0:00:42
   ---------------- ----------------------- 17.3/41.3 MB 587.6 kB/s eta 0:00:41
   ---------------- ----------------------- 17.3/41.3 MB 587.6 kB/s eta 0:00:41
   ----------------- ---------------------- 17.6/41.3 MB 587.4 kB/s eta 0:00:41
   ----------------- ---------------------- 17.6/41.3 MB 587.4 kB/s eta 0:00:41
   ----------------- ---------------------- 17.8/41.3 MB 587.6 kB/s eta 0:00:40
   ----------------- ---------------------- 17.8/41.3 MB 587.6 kB/s eta 0:00:40
   ----------------- ---------------------- 18.1/41.3 MB 588.2 kB/s eta 0:00:40
   ----------------- ---------------------- 18.1/41.3 MB 588.2 kB/s eta 0:00:40
   ----------------- ---------------------- 18.4/41.3 MB 586.4 kB/s eta 0:00:40
   ----------------- ---------------------- 18.4/41.3 MB 586.4 kB/s eta 0:00:40
   ------------------ --------------------- 18.6/41.3 MB 585.8 kB/s eta 0:00:39
   ------------------ --------------------- 18.6/41.3 MB 585.8 kB/s eta 0:00:39
   ------------------ --------------------- 18.9/41.3 MB 587.3 kB/s eta 0:00:39
   ------------------ --------------------- 18.9/41.3 MB 587.3 kB/s eta 0:00:39
   ------------------ --------------------- 18.9/41.3 MB 587.3 kB/s eta 0:00:39
   ------------------ --------------------- 19.1/41.3 MB 586.7 kB/s eta 0:00:38
   ------------------ --------------------- 19.1/41.3 MB 586.7 kB/s eta 0:00:38
   ------------------ --------------------- 19.4/41.3 MB 587.0 kB/s eta 0:00:38
   ------------------ --------------------- 19.4/41.3 MB 587.0 kB/s eta 0:00:38
   ------------------- -------------------- 19.7/41.3 MB 586.4 kB/s eta 0:00:37
   ------------------- -------------------- 19.7/41.3 MB 586.4 kB/s eta 0:00:37
   ------------------- -------------------- 19.9/41.3 MB 586.7 kB/s eta 0:00:37
   ------------------- -------------------- 19.9/41.3 MB 586.7 kB/s eta 0:00:37
   ------------------- -------------------- 20.2/41.3 MB 586.7 kB/s eta 0:00:36
   ------------------- -------------------- 20.2/41.3 MB 586.7 kB/s eta 0:00:36
   ------------------- -------------------- 20.4/41.3 MB 587.0 kB/s eta 0:00:36
   ------------------- -------------------- 20.4/41.3 MB 587.0 kB/s eta 0:00:36
   -------------------- ------------------- 20.7/41.3 MB 587.3 kB/s eta 0:00:35
   -------------------- ------------------- 20.7/41.3 MB 587.3 kB/s eta 0:00:35
   -------------------- ------------------- 21.0/41.3 MB 586.7 kB/s eta 0:00:35
   -------------------- ------------------- 21.0/41.3 MB 586.7 kB/s eta 0:00:35
   -------------------- ------------------- 21.2/41.3 MB 587.9 kB/s eta 0:00:35
   -------------------- ------------------- 21.2/41.3 MB 587.9 kB/s eta 0:00:35
   -------------------- ------------------- 21.5/41.3 MB 587.9 kB/s eta 0:00:34
   -------------------- ------------------- 21.5/41.3 MB 587.9 kB/s eta 0:00:34
   --------------------- ------------------ 21.8/41.3 MB 587.3 kB/s eta 0:00:34
   --------------------- ------------------ 21.8/41.3 MB 587.3 kB/s eta 0:00:34
   --------------------- ------------------ 22.0/41.3 MB 589.1 kB/s eta 0:00:33
   --------------------- ------------------ 22.0/41.3 MB 589.1 kB/s eta 0:00:33
   --------------------- ------------------ 22.3/41.3 MB 588.5 kB/s eta 0:00:33
   --------------------- ------------------ 22.3/41.3 MB 588.5 kB/s eta 0:00:33
   --------------------- ------------------ 22.5/41.3 MB 588.5 kB/s eta 0:00:32
   --------------------- ------------------ 22.5/41.3 MB 588.5 kB/s eta 0:00:32
   ---------------------- ----------------- 22.8/41.3 MB 589.4 kB/s eta 0:00:32
   ---------------------- ----------------- 22.8/41.3 MB 589.4 kB/s eta 0:00:32
   ---------------------- ----------------- 23.1/41.3 MB 588.5 kB/s eta 0:00:31
   ---------------------- ----------------- 23.1/41.3 MB 588.5 kB/s eta 0:00:31
   ---------------------- ----------------- 23.3/41.3 MB 588.5 kB/s eta 0:00:31
   ---------------------- ----------------- 23.3/41.3 MB 588.5 kB/s eta 0:00:31
   ---------------------- ----------------- 23.6/41.3 MB 588.5 kB/s eta 0:00:31
   ---------------------- ----------------- 23.6/41.3 MB 588.5 kB/s eta 0:00:31
   ----------------------- ---------------- 23.9/41.3 MB 588.8 kB/s eta 0:00:30
   ----------------------- ---------------- 23.9/41.3 MB 588.8 kB/s eta 0:00:30
   ----------------------- ---------------- 24.1/41.3 MB 589.1 kB/s eta 0:00:30
   ----------------------- ---------------- 24.1/41.3 MB 589.1 kB/s eta 0:00:30
   ----------------------- ---------------- 24.4/41.3 MB 588.8 kB/s eta 0:00:29
   ----------------------- ---------------- 24.4/41.3 MB 588.8 kB/s eta 0:00:29
   ----------------------- ---------------- 24.6/41.3 MB 588.8 kB/s eta 0:00:29
   ----------------------- ---------------- 24.6/41.3 MB 588.8 kB/s eta 0:00:29
   ------------------------ --------------- 24.9/41.3 MB 588.2 kB/s eta 0:00:28
   ------------------------ --------------- 24.9/41.3 MB 588.2 kB/s eta 0:00:28
   ------------------------ --------------- 25.2/41.3 MB 588.8 kB/s eta 0:00:28
   ------------------------ --------------- 25.2/41.3 MB 588.8 kB/s eta 0:00:28
   ------------------------ --------------- 25.4/41.3 MB 589.1 kB/s eta 0:00:27
   ------------------------ --------------- 25.4/41.3 MB 589.1 kB/s eta 0:00:27
   ------------------------ --------------- 25.7/41.3 MB 589.1 kB/s eta 0:00:27
   ------------------------ --------------- 25.7/41.3 MB 589.1 kB/s eta 0:00:27
   ------------------------- -------------- 26.0/41.3 MB 589.4 kB/s eta 0:00:26
   ------------------------- -------------- 26.0/41.3 MB 589.4 kB/s eta 0:00:26
   ------------------------- -------------- 26.2/41.3 MB 590.1 kB/s eta 0:00:26
   ------------------------- -------------- 26.2/41.3 MB 590.1 kB/s eta 0:00:26
   ------------------------- -------------- 26.5/41.3 MB 589.7 kB/s eta 0:00:26
   ------------------------- -------------- 26.5/41.3 MB 589.7 kB/s eta 0:00:26
   ------------------------- -------------- 26.7/41.3 MB 589.7 kB/s eta 0:00:25
   ------------------------- -------------- 26.7/41.3 MB 589.7 kB/s eta 0:00:25
   -------------------------- ------------- 27.0/41.3 MB 589.8 kB/s eta 0:00:25
   -------------------------- ------------- 27.0/41.3 MB 589.8 kB/s eta 0:00:25
   -------------------------- ------------- 27.3/41.3 MB 590.1 kB/s eta 0:00:24
   -------------------------- ------------- 27.3/41.3 MB 590.1 kB/s eta 0:00:24
   -------------------------- ------------- 27.5/41.3 MB 590.1 kB/s eta 0:00:24
   -------------------------- ------------- 27.5/41.3 MB 590.1 kB/s eta 0:00:24
   -------------------------- ------------- 27.8/41.3 MB 590.7 kB/s eta 0:00:23
   -------------------------- ------------- 27.8/41.3 MB 590.7 kB/s eta 0:00:23
   --------------------------- ------------ 28.0/41.3 MB 590.4 kB/s eta 0:00:23
   --------------------------- ------------ 28.0/41.3 MB 590.4 kB/s eta 0:00:23
   --------------------------- ------------ 28.3/41.3 MB 591.0 kB/s eta 0:00:22
   --------------------------- ------------ 28.3/41.3 MB 591.0 kB/s eta 0:00:22
   --------------------------- ------------ 28.6/41.3 MB 590.4 kB/s eta 0:00:22
   --------------------------- ------------ 28.6/41.3 MB 590.4 kB/s eta 0:00:22
   --------------------------- ------------ 28.8/41.3 MB 591.0 kB/s eta 0:00:22
   --------------------------- ------------ 28.8/41.3 MB 591.0 kB/s eta 0:00:22
   ---------------------------- ----------- 29.1/41.3 MB 591.3 kB/s eta 0:00:21
   ---------------------------- ----------- 29.1/41.3 MB 591.3 kB/s eta 0:00:21
   ---------------------------- ----------- 29.1/41.3 MB 591.3 kB/s eta 0:00:21
   ---------------------------- ----------- 29.4/41.3 MB 591.6 kB/s eta 0:00:21
   ---------------------------- ----------- 29.4/41.3 MB 591.6 kB/s eta 0:00:21
   ---------------------------- ----------- 29.6/41.3 MB 590.7 kB/s eta 0:00:20
   ---------------------------- ----------- 29.6/41.3 MB 590.7 kB/s eta 0:00:20
   ---------------------------- ----------- 29.9/41.3 MB 588.2 kB/s eta 0:00:20
   ---------------------------- ----------- 29.9/41.3 MB 588.2 kB/s eta 0:00:20
   ----------------------------- ---------- 30.1/41.3 MB 589.1 kB/s eta 0:00:19
   ----------------------------- ---------- 30.1/41.3 MB 589.1 kB/s eta 0:00:19
   ----------------------------- ---------- 30.4/41.3 MB 589.8 kB/s eta 0:00:19
   ----------------------------- ---------- 30.4/41.3 MB 589.8 kB/s eta 0:00:19
   ----------------------------- ---------- 30.7/41.3 MB 590.1 kB/s eta 0:00:18
   ----------------------------- ---------- 30.7/41.3 MB 590.1 kB/s eta 0:00:18
   ----------------------------- ---------- 30.9/41.3 MB 590.1 kB/s eta 0:00:18
   ----------------------------- ---------- 30.9/41.3 MB 590.1 kB/s eta 0:00:18
   ----------------------------- ---------- 30.9/41.3 MB 590.1 kB/s eta 0:00:18
   ------------------------------ --------- 31.2/41.3 MB 589.1 kB/s eta 0:00:18
   ------------------------------ --------- 31.2/41.3 MB 589.1 kB/s eta 0:00:18
   ------------------------------ --------- 31.5/41.3 MB 588.2 kB/s eta 0:00:17
   ------------------------------ --------- 31.5/41.3 MB 588.2 kB/s eta 0:00:17

In [2]:
pip install ipywidgets

Requirement already satisfied: ipywidgets in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (8.1.7)
Requirement already satisfied: comm>=0.1.3 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipywidgets) (8.30.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipywidgets) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipywidgets) (3.0.15)
Requirement already satisfied: decorator in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: exceptiongroup in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.2.0)
Requirement already satisfied: typing-extensions>=4.6 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (4.15.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: executing>=1.2.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure_eval in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

WARNING: Error parsing dependencies of certifi: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\envs\\sqlenv\\lib\\site-packages\\certifi-2025.10.5.dist-info\\METADATA'

In [3]:
pip install chart-studio

Collecting chart-studio
  Downloading chart_studio-1.1.0-py3-none-any.whl.metadata (1.3 kB)
Collecting plotly (from chart-studio)
  Downloading plotly-6.5.2-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: requests in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from chart-studio) (2.32.5)
Collecting retrying>=1.3.3 (from chart-studio)
  Downloading retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: six in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from chart-studio) (1.17.0)
Collecting narwhals>=1.15.1 (from plotly->chart-studio)
  Downloading narwhals-2.16.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from plotly->chart-studio) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from requests->chart-studio) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from requests->chart-studio) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from requests->chart-studio) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from requests->chart-studio) (2025.10.5)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\envs\\sqlenv\\lib\\site-packages\\certifi-2025.10.5.dist-info\\METADATA'

In [4]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-23.0.0-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
Downloading pyarrow-23.0.0-cp310-cp310-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.5 MB ? eta -:--:--
    --------------------------------------- 0.5/27.5 MB 672.2 kB/s eta 0:00:41
    --------------------------------------- 0.5/27.5 MB 672.2 kB/s eta 0:00:41
   - -------------------------------------- 0.8/27.5 MB 621.9 kB/s eta 0:00:44
   - -------------------------------------- 0.8/27.5 MB 621.9 kB/s eta 0:00:44
   - -------------------------------------- 1.0/27.5 MB 613.9 kB/s eta 0:00:44
   - -------------------------------------- 1.0/27.5 MB 613.9 kB/s eta 0:00:44
   - -------------------------------------- 1.3/27.5 MB 604.7 kB/s eta 0:00:44
   - -------------------------------------- 1.3/27.5 MB 604.7 kB/s eta 0:00:44
   - -------------------------------------- 1.3/27.5 MB 604.7 kB/s eta 0:00:44
   -- ------------------------------------- 1.6/27.5 MB 599.3 kB/s eta 0:00:44
   -- ------------------------------------- 1.6/27.5 MB 599.3 kB/s eta 0:00:44
   -- ------------------------------------- 1.8/27.5 MB 599.2 kB/s eta 0:00:43
   -- ------------------------------------- 1.8/27.5 MB 599.2 kB/s eta 0:00:43
   --- ------------------------------------ 2.1/27.5 MB 602.2 kB/s eta 0:00:43
   --- ------------------------------------ 2.1/27.5 MB 602.2 kB/s eta 0:00:43
   --- ------------------------------------ 2.4/27.5 MB 601.9 kB/s eta 0:00:42
   --- ------------------------------------ 2.4/27.5 MB 601.9 kB/s eta 0:00:42
   --- ------------------------------------ 2.6/27.5 MB 596.8 kB/s eta 0:00:42
   --- ------------------------------------ 2.6/27.5 MB 596.8 kB/s eta 0:00:42
   ---- ----------------------------------- 2.9/27.5 MB 597.1 kB/s eta 0:00:42
   ---- ----------------------------------- 2.9/27.5 MB 597.1 kB/s eta 0:00:42
   ---- ----------------------------------- 3.1/27.5 MB 597.3 kB/s eta 0:00:41
   ---- ----------------------------------- 3.1/27.5 MB 597.3 kB/s eta 0:00:41
   ---- ----------------------------------- 3.4/27.5 MB 597.5 kB/s eta 0:00:41
   ---- ----------------------------------- 3.4/27.5 MB 597.5 kB/s eta 0:00:41
   ----- ---------------------------------- 3.7/27.5 MB 592.7 kB/s eta 0:00:41
   ----- ---------------------------------- 3.7/27.5 MB 592.7 kB/s eta 0:00:41
   ----- ---------------------------------- 3.9/27.5 MB 594.6 kB/s eta 0:00:40
   ----- ---------------------------------- 3.9/27.5 MB 594.6 kB/s eta 0:00:40
   ------ --------------------------------- 4.2/27.5 MB 595.0 kB/s eta 0:00:40
   ------ --------------------------------- 4.2/27.5 MB 595.0 kB/s eta 0:00:40
   ------ --------------------------------- 4.5/27.5 MB 595.2 kB/s eta 0:00:39
   ------ --------------------------------- 4.5/27.5 MB 595.2 kB/s eta 0:00:39
   ------ --------------------------------- 4.7/27.5 MB 593.0 kB/s eta 0:00:39
   ------ --------------------------------- 4.7/27.5 MB 593.0 kB/s eta 0:00:39
   ------- -------------------------------- 5.0/27.5 MB 591.0 kB/s eta 0:00:39
   ------- -------------------------------- 5.0/27.5 MB 591.0 kB/s eta 0:00:39
   ------- -------------------------------- 5.2/27.5 MB 593.7 kB/s eta 0:00:38
   ------- -------------------------------- 5.2/27.5 MB 593.7 kB/s eta 0:00:38
   ------- -------------------------------- 5.5/27.5 MB 593.9 kB/s eta 0:00:38
   ------- -------------------------------- 5.5/27.5 MB 593.9 kB/s eta 0:00:38
   -------- ------------------------------- 5.8/27.5 MB 594.2 kB/s eta 0:00:37
   -------- ------------------------------- 5.8/27.5 MB 594.2 kB/s eta 0:00:37
   -------- ------------------------------- 6.0/27.5 MB 593.5 kB/s eta 0:00:37
   -------- ------------------------------- 6.0/27.5 MB 593.5 kB/s eta 0:00:37
   --------- ------------------------------ 6.3/27.5 MB 594.6 kB/s eta 0:00:36
   --------- ------------------------------ 6.3/27.5 MB 594.6 kB/s eta 0:00:36
   --------- ------------------------------ 6.6/27.5 MB 593.9 kB/s eta 0:00:36
   --------- ------------------------------ 6.6/27.5 MB 593.9 kB/s eta 0:00:36
   --------- ------------------------------ 6.8/27.5 MB 592.4 kB/s eta 0:00:35
   --------- ------------------------------ 6.8/27.5 MB 592.4 kB/s eta 0:00:35
   ---------- ----------------------------- 7.1/27.5 MB 592.7 kB/s eta 0:00:35
   ---------- ----------------------------- 7.1/27.5 MB 592.7 kB/s eta 0:00:35
   ---------- ----------------------------- 7.3/27.5 MB 592.1 kB/s eta 0:00:35
   ---------- ----------------------------- 7.3/27.5 MB 592.1 kB/s eta 0:00:35
   ----------- ---------------------------- 7.6/27.5 MB 592.4 kB/s eta 0:00:34
   ----------- ---------------------------- 7.6/27.5 MB 592.4 kB/s eta 0:00:34
   ----------- ---------------------------- 7.9/27.5 MB 592.6 kB/s eta 0:00:34
   ----------- ---------------------------- 7.9/27.5 MB 592.6 kB/s eta 0:00:34
   ----------- ---------------------------- 8.1/27.5 MB 592.1 kB/s eta 0:00:33
   ----------- ---------------------------- 8.1/27.5 MB 592.1 kB/s eta 0:00:33
   ------------ --------------------------- 8.4/27.5 MB 591.0 kB/s eta 0:00:33
   ------------ --------------------------- 8.4/27.5 MB 591.0 kB/s eta 0:00:33
   ------------ --------------------------- 8.7/27.5 MB 591.3 kB/s eta 0:00:32
   ------------ --------------------------- 8.7/27.5 MB 591.3 kB/s eta 0:00:32
   ------------ --------------------------- 8.9/27.5 MB 591.5 kB/s eta 0:00:32
   ------------ --------------------------- 8.9/27.5 MB 591.5 kB/s eta 0:00:32
   ------------- -------------------------- 9.2/27.5 MB 591.1 kB/s eta 0:00:32
   ------------- -------------------------- 9.2/27.5 MB 591.1 kB/s eta 0:00:32
   ------------- -------------------------- 9.4/27.5 MB 591.4 kB/s eta 0:00:31
   ------------- -------------------------- 9.4/27.5 MB 591.4 kB/s eta 0:00:31
   ------------- -------------------------- 9.4/27.5 MB 591.4 kB/s eta 0:00:31
   -------------- ------------------------- 9.7/27.5 MB 591.0 kB/s eta 0:00:31
   -------------- ------------------------- 10.0/27.5 MB 591.2 kB/s eta 0:00:30
   -------------- ------------------------- 10.0/27.5 MB 591.2 kB/s eta 0:00:30
   -------------- ------------------------- 10.2/27.5 MB 592.0 kB/s eta 0:00:30
   -------------- ------------------------- 10.2/27.5 MB 592.0 kB/s eta 0:00:30
   --------------- ------------------------ 10.5/27.5 MB 591.6 kB/s eta 0:00:29
   --------------- ------------------------ 10.5/27.5 MB 591.6 kB/s eta 0:00:29
   --------------- ------------------------ 10.5/27.5 MB 591.6 kB/s eta 0:00:29
   --------------- ------------------------ 10.7/27.5 MB 591.3 kB/s eta 0:00:29
   --------------- ------------------------ 10.7/27.5 MB 591.3 kB/s eta 0:00:29
   --------------- ------------------------ 11.0/27.5 MB 590.4 kB/s eta 0:00:28
   --------------- ------------------------ 11.0/27.5 MB 590.4 kB/s eta 0:00:28
   ---------------- ----------------------- 11.3/27.5 MB 590.7 kB/s eta 0:00:28
   ---------------- ----------------------- 11.3/27.5 MB 590.7 kB/s eta 0:00:28
   ---------------- ----------------------- 11.5/27.5 MB 590.8 kB/s eta 0:00:28
   ---------------- ----------------------- 11.5/27.5 MB 590.8 kB/s eta 0:00:28
   ----------------- ---------------------- 11.8/27.5 MB 590.6 kB/s eta 0:00:27
   ----------------- ---------------------- 11.8/27.5 MB 590.6 kB/s eta 0:00:27
   ----------------- ---------------------- 12.1/27.5 MB 590.3 kB/s eta 0:00:27
   ----------------- ---------------------- 12.1/27.5 MB 590.3 kB/s eta 0:00:27
   ----------------- ---------------------- 12.3/27.5 MB 590.5 kB/s eta 0:00:26
   ----------------- ---------------------- 12.3/27.5 MB 590.5 kB/s eta 0:00:26
   ------------------ --------------------- 12.6/27.5 MB 589.8 kB/s eta 0:00:26
   ------------------ --------------------- 12.6/27.5 MB 589.8 kB/s eta 0:00:26
   ------------------ --------------------- 12.8/27.5 MB 589.1 kB/s eta 0:00:25
   ------------------ --------------------- 12.8/27.5 MB 589.1 kB/s eta 0:00:25
   ------------------- -------------------- 13.1/27.5 MB 587.2 kB/s eta 0:00:25
   ------------------- -------------------- 13.1/27.5 MB 587.2 kB/s eta 0:00:25
   ------------------- -------------------- 13.4/27.5 MB 587.5 kB/s eta 0:00:25
   ------------------- -------------------- 13.4/27.5 MB 587.5 kB/s eta 0:00:25
   ------------------- -------------------- 13.6/27.5 MB 588.5 kB/s eta 0:00:24
   ------------------- -------------------- 13.6/27.5 MB 588.5 kB/s eta 0:00:24
   -------------------- ------------------- 13.9/27.5 MB 588.7 kB/s eta 0:00:24
   -------------------- ------------------- 13.9/27.5 MB 588.7 kB/s eta 0:00:24
   -------------------- ------------------- 14.2/27.5 MB 588.5 kB/s eta 0:00:23
   -------------------- ------------------- 14.2/27.5 MB 588.5 kB/s eta 0:00:23
   -------------------- ------------------- 14.4/27.5 MB 588.3 kB/s eta 0:00:23
   -------------------- ------------------- 14.4/27.5 MB 588.3 kB/s eta 0:00:23
   --------------------- ------------------ 14.7/27.5 MB 588.5 kB/s eta 0:00:22
   --------------------- ------------------ 14.7/27.5 MB 588.5 kB/s eta 0:00:22
   --------------------- ------------------ 14.9/27.5 MB 588.3 kB/s eta 0:00:22
   --------------------- ------------------ 14.9/27.5 MB 588.3 kB/s eta 0:00:22
   ---------------------- ----------------- 15.2/27.5 MB 588.5 kB/s eta 0:00:21
   ---------------------- ----------------- 15.2/27.5 MB 588.5 kB/s eta 0:00:21
   ---------------------- ----------------- 15.2/27.5 MB 588.5 kB/s eta 0:00:21
   ---------------------- ----------------- 15.5/27.5 MB 588.3 kB/s eta 0:00:21
   ---------------------- ----------------- 15.5/27.5 MB 588.3 kB/s eta 0:00:21
   ---------------------- ----------------- 15.7/27.5 MB 588.1 kB/s eta 0:00:21
   ----------------------- ---------------- 16.0/27.5 MB 589.0 kB/s eta 0:00:20
   ----------------------- ---------------- 16.0/27.5 MB 589.0 kB/s eta 0:00:20
   ----------------------- ---------------- 16.0/27.5 MB 589.0 kB/s eta 0:00:20
   ----------------------- ---------------- 16.3/27.5 MB 588.5 kB/s eta 0:00:20
   ----------------------- ---------------- 16.3/27.5 MB 588.5 kB/s eta 0:00:20
   ----------------------- ---------------- 16.5/27.5 MB 588.3 kB/s eta 0:00:19
   ----------------------- ---------------- 16.5/27.5 MB 588.3 kB/s eta 0:00:19
   ------------------------ --------------- 16.8/27.5 MB 588.5 kB/s eta 0:00:19
   ------------------------ --------------- 16.8/27.5 MB 588.5 kB/s eta 0:00:19
   ------------------------ --------------- 17.0/27.5 MB 588.7 kB/s eta 0:00:18
   ------------------------ --------------- 17.0/27.5 MB 588.7 kB/s eta 0:00:18
   ------------------------- -------------- 17.3/27.5 MB 588.5 kB/s eta 0:00:18
   ------------------------- -------------- 17.3/27.5 MB 588.5 kB/s eta 0:00:18
   ------------------------- -------------- 17.6/27.5 MB 589.0 kB/s eta 0:00:17
   ------------------------- -------------- 17.6/27.5 MB 589.0 kB/s eta 0:00:17
   ------------------------- -------------- 17.8/27.5 MB 589.4 kB/s eta 0:00:17
   ------------------------- -------------- 17.8/27.5 MB 589.4 kB/s eta 0:00:17
   -------------------------- ------------- 18.1/27.5 MB 587.6 kB/s eta 0:00:17
   -------------------------- ------------- 18.1/27.5 MB 587.6 kB/s eta 0:00:17
   -------------------------- ------------- 18.4/27.5 MB 588.2 kB/s eta 0:00:16
   -------------------------- ------------- 18.4/27.5 MB 588.2 kB/s eta 0:00:16
   --------------------------- ------------ 18.6/27.5 MB 587.9 kB/s eta 0:00:16
   --------------------------- ------------ 18.6/27.5 MB 587.9 kB/s eta 0:00:16
   --------------------------- ------------ 18.9/27.5 MB 588.2 kB/s eta 0:00:15
   --------------------------- ------------ 18.9/27.5 MB 588.2 kB/s eta 0:00:15
   --------------------------- ------------ 19.1/27.5 MB 588.5 kB/s eta 0:00:15
   --------------------------- ------------ 19.1/27.5 MB 588.5 kB/s eta 0:00:15
   ---------------------------- ----------- 19.4/27.5 MB 587.9 kB/s eta 0:00:14
   ---------------------------- ----------- 19.4/27.5 MB 587.9 kB/s eta 0:00:14
   ---------------------------- ----------- 19.7/27.5 MB 587.6 kB/s eta 0:00:14
   ---------------------------- ----------- 19.7/27.5 MB 587.6 kB/s eta 0:00:14
   ---------------------------- ----------- 19.9/27.5 MB 587.3 kB/s eta 0:00:13
   ---------------------------- ----------- 19.9/27.5 MB 587.3 kB/s eta 0:00:13
   ----------------------------- ---------- 20.2/27.5 MB 588.2 kB/s eta 0:00:13
   ----------------------------- ---------- 20.2/27.5 MB 588.2 kB/s eta 0:00:13
   ----------------------------- ---------- 20.4/27.5 MB 588.2 kB/s eta 0:00:13
   ----------------------------- ---------- 20.4/27.5 MB 588.2 kB/s eta 0:00:13
   ------------------------------ --------- 20.7/27.5 MB 587.6 kB/s eta 0:00:12
   ------------------------------ --------- 20.7/27.5 MB 587.6 kB/s eta 0:00:12
   ------------------------------ --------- 21.0/27.5 MB 587.6 kB/s eta 0:00:12
   ------------------------------ --------- 21.0/27.5 MB 587.6 kB/s eta 0:00:12
   ------------------------------ --------- 21.2/27.5 MB 588.8 kB/s eta 0:00:11
   ------------------------------ --------- 21.2/27.5 MB 588.8 kB/s eta 0:00:11
   ------------------------------- -------- 21.5/27.5 MB 588.2 kB/s eta 0:00:11
   ------------------------------- -------- 21.5/27.5 MB 588.2 kB/s eta 0:00:11
   ------------------------------- -------- 21.8/27.5 MB 587.9 kB/s eta 0:00:10
   ------------------------------- -------- 21.8/27.5 MB 587.9 kB/s eta 0:00:10
   ------------------------------- -------- 22.0/27.5 MB 587.9 kB/s eta 0:00:10
   ------------------------------- -------- 22.0/27.5 MB 587.9 kB/s eta 0:00:10
   -------------------------------- ------- 22.3/27.5 MB 588.8 kB/s eta 0:00:09
   -------------------------------- ------- 22.3/27.5 MB 588.8 kB/s eta 0:00:09
   -------------------------------- ------- 22.5/27.5 MB 589.1 kB/s eta 0:00:09
   -------------------------------- ------- 22.5/27.5 MB 589.1 kB/s eta 0:00:09
   --------------------------------- ------ 22.8/27.5 MB 588.2 kB/s eta 0:00:09
   --------------------------------- ------ 22.8/27.5 MB 588.2 kB/s eta 0:00:09
   --------------------------------- ------ 23.1/27.5 MB 588.2 kB/s eta 0:00:08
   --------------------------------- ------ 23.1/27.5 MB 588.2 kB/s eta 0:00:08
   --------------------------------- ------ 23.3/27.5 MB 587.9 kB/s eta 0:00:08
   --------------------------------- ------ 23.3/27.5 MB 587.9 kB/s eta 0:00:08
   ---------------------------------- ----- 23.6/27.5 MB 588.5 kB/s eta 0:00:07
   ---------------------------------- ----- 23.6/27.5 MB 588.5 kB/s eta 0:00:07
   ---------------------------------- ----- 23.9/27.5 MB 587.9 kB/s eta 0:00:07
   ---------------------------------- ----- 23.9/27.5 MB 587.9 kB/s eta 0:00:07
   ----------------------------------- ---- 24.1/27.5 MB 587.9 kB/s eta 0:00:06
   ----------------------------------- ---- 24.1/27.5 MB 587.9 kB/s eta 0:00:06
   ----------------------------------- ---- 24.1/27.5 MB 587.9 kB/s eta 0:00:06
   ----------------------------------- ---- 24.4/27.5 MB 588.8 kB/s eta 0:00:06
   ----------------------------------- ---- 24.4/27.5 MB 588.8 kB/s eta 0:00:06
   ----------------------------------- ---- 24.6/27.5 MB 588.8 kB/s eta 0:00:05
   ----------------------------------- ---- 24.6/27.5 MB 588.8 kB/s eta 0:00:05
   ------------------------------------ --- 24.9/27.5 MB 588.8 kB/s eta 0:00:05
   ------------------------------------ --- 24.9/27.5 MB 588.8 kB/s eta 0:00:05
   ------------------------------------ --- 25.2/27.5 MB 588.8 kB/s eta 0:00:05
   ------------------------------------ --- 25.2/27.5 MB 588.8 kB/s eta 0:00:05
   ------------------------------------ --- 25.4/27.5 MB 588.8 kB/s eta 0:00:04
   ------------------------------------ --- 25.4/27.5 MB 588.8 kB/s eta 0:00:04
   ------------------------------------- -- 25.7/27.5 MB 588.8 kB/s eta 0:00:04
   ------------------------------------- -- 25.7/27.5 MB 588.8 kB/s eta 0:00:04
   ------------------------------------- -- 26.0/27.5 MB 588.8 kB/s eta 0:00:03
   ------------------------------------- -- 26.0/27.5 MB 588.8 kB/s eta 0:00:03
   -------------------------------------- - 26.2/27.5 MB 589.4 kB/s eta 0:00:03
   -------------------------------------- - 26.2/27.5 MB 589.4 kB/s eta 0:00:03
   -------------------------------------- - 26.5/27.5 MB 589.8 kB/s eta 0:00:02
   -------------------------------------- - 26.5/27.5 MB 589.8 kB/s eta 0:00:02
   -------------------------------------- - 26.7/27.5 MB 588.8 kB/s eta 0:00:02
   -------------------------------------- - 26.7/27.5 MB 588.8 kB/s eta 0:00:02
   ---------------------------------------  27.0/27.5 MB 589.7 kB/s eta 0:00:01
   ---------------------------------------  27.0/27.5 MB 589.7 kB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 589.7 kB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 589.7 kB/s eta 0:00:01
   ---------------------------------------  27.5/27.5 MB 589.4 kB/s eta 0:00:01
   ---------------------------------------- 27.5/27.5 MB 573.2 kB/s  0:00:47
Installing collected packages: pyarrow
Successfully installed pyarrow-23.0.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Error parsing dependencies of certifi: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\envs\\sqlenv\\lib\\site-packages\\certifi-2025.10.5.dist-info\\METADATA'

In [5]:
pip install cufflinks

Collecting cufflinksNote: you may need to restart the kernel to use updated packages.

  DEPRECATION: Building 'cufflinks' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'cufflinks'. Discussion can be found at https://github.com/pypa/pip/issues/6334
WARNING: Error parsing dependencies of certifi: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\envs\\sqlenv\\lib\\site-packages\\certifi-2025.10.5.dist-info\\METADATA'

  Downloading cufflinks-0.17.3.tar.gz (81 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.9.2 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from cufflinks) (2.2.5)
Requirement already satisfied: pandas>=0.19.2 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from cufflinks) (2.3.3)
Collecting plotly>=4.1.1 (from cufflinks)
  Using cached plotly-6.5.2-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: six>=1.9.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from cufflinks) (1.17.0)
Collecting colorlover>=0.2.1 (from cufflinks)
  Downloading colorlover-0.3.0-py3-none-any.whl.metadata (421 bytes)
Requirement already satisfied: setuptools>=34.4.1 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from cufflinks) (80.9.0)
Requirement already satisfied: ipython>=5.3.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from cufflinks) (8.30.0)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from cufflinks) (8.1.7)
Requirement already satisfied: decorator in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.2.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (2.19.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.14.3)
Requirement already satisfied: exceptiongroup in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (1.2.0)
Requirement already satisfied: typing-extensions>=4.6 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (4.15.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.4.6)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->cufflinks) (0.2.13)
Requirement already satisfied: comm>=0.1.3 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.1)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.0.15)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->cufflinks) (0.8.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from pandas>=0.19.2->cufflinks) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from pandas>=0.19.2->cufflinks) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from pandas>=0.19.2->cufflinks) (2025.2)
Collecting narwhals>=1.15.1 (from plotly>=4.1.1->cufflinks)
  Using cached narwhals-2.16.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from plotly>=4.1.1->cufflinks) (25.0)
Requirement already satisfied: executing>=1.2.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from stack-data->ipython>=5.3.0->cufflinks) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from stack-data->ipython>=5.3.0->cufflinks) (3.0.0)
Requirement already satisfied: pure_eval in c:\programdata\anaconda3\envs\sqlenv\lib\site-packages (from stack-data->ipython>=5.3.0->cufflinks) (0.2.3)
Downloading colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Downloading plotly-6.5.2-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 764.3 kB/s eta 0:00:13
   -- ------------------------------------- 0.5/9.9 MB 764.3 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/9.9 MB 685.3 kB/s eta 0:00:14
   --- ------------------------------------ 0.8/9.9 MB 685.3 kB/s eta 0:00:14
   ---- ----------------------------------- 1.0/9.9 MB 653.7 kB/s eta 0:00:14
   ---- ----------------------------------- 1.0/9.9 MB 653.7 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/9.9 MB 645.3 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/9.9 MB 645.3 kB/s eta 0:00:14
   ------ --------------------------------- 1.6/9.9 MB 635.7 kB/s eta 0:00:14
   ------ --------------------------------- 1.6/9.9 MB 635.7 kB/s eta 0:00:14
   ------- -------------------------------- 1.8/9.9 MB 629.1 kB/s eta 0:00:13
   ------- -------------------------------- 1.8/9.9 MB 629.1 kB/s eta 0:00:13
   -------- ------------------------------- 2.1/9.9 MB 624.8 kB/s eta 0:00:13
   -------- ------------------------------- 2.1/9.9 MB 624.8 kB/s eta 0:00:13
   --------- ------------------------------ 2.4/9.9 MB 624.3 kB/s eta 0:00:13
   --------- ------------------------------ 2.4/9.9 MB 624.3 kB/s eta 0:00:13
   ---------- ----------------------------- 2.6/9.9 MB 618.9 kB/s eta 0:00:12
   ---------- ----------------------------- 2.6/9.9 MB 618.9 kB/s eta 0:00:12
   ----------- ---------------------------- 2.9/9.9 MB 619.1 kB/s eta 0:00:12
   ----------- ---------------------------- 2.9/9.9 MB 619.1 kB/s eta 0:00:12
   ------------ --------------------------- 3.1/9.9 MB 617.2 kB/s eta 0:00:11
   ------------ --------------------------- 3.1/9.9 MB 617.2 kB/s eta 0:00:11
   ------------- -------------------------- 3.4/9.9 MB 615.7 kB/s eta 0:00:11
   ------------- -------------------------- 3.4/9.9 MB 615.7 kB/s eta 0:00:11
   -------------- ------------------------- 3.7/9.9 MB 616.1 kB/s eta 0:00:11
   -------------- ------------------------- 3.7/9.9 MB 616.1 kB/s eta 0:00:11
   --------------- ------------------------ 3.9/9.9 MB 614.9 kB/s eta 0:00:10
   --------------- ------------------------ 3.9/9.9 MB 614.9 kB/s eta 0:00:10
   ---------------- ----------------------- 4.2/9.9 MB 613.8 kB/s eta 0:00:10
   ---------------- ----------------------- 4.2/9.9 MB 613.8 kB/s eta 0:00:10
   ------------------ --------------------- 4.5/9.9 MB 612.9 kB/s eta 0:00:09
   ------------------ --------------------- 4.5/9.9 MB 612.9 kB/s eta 0:00:09
   ------------------- -------------------- 4.7/9.9 MB 612.1 kB/s eta 0:00:09
   -------------------- ------------------- 5.0/9.9 MB 611.4 kB/s eta 0:00:09
   -------------------- ------------------- 5.0/9.9 MB 611.4 kB/s eta 0:00:09
   -------------------- ------------------- 5.0/9.9 MB 611.4 kB/s eta 0:00:09
   --------------------- ------------------ 5.2/9.9 MB 609.5 kB/s eta 0:00:08
   --------------------- ------------------ 5.2/9.9 MB 609.5 kB/s eta 0:00:08
   ---------------------- ----------------- 5.5/9.9 MB 606.8 kB/s eta 0:00:08
   ---------------------- ----------------- 5.5/9.9 MB 606.8 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.9 MB 604.3 kB/s eta 0:00:07
   ----------------------- ---------------- 5.8/9.9 MB 604.3 kB/s eta 0:00:07
   ------------------------ --------------- 6.0/9.9 MB 605.1 kB/s eta 0:00:07
   ------------------------ --------------- 6.0/9.9 MB 605.1 kB/s eta 0:00:07
   ------------------------- -------------- 6.3/9.9 MB 602.9 kB/s eta 0:00:06
   ------------------------- -------------- 6.3/9.9 MB 602.9 kB/s eta 0:00:06
   -------------------------- ------------- 6.6/9.9 MB 601.0 kB/s eta 0:00:06
   -------------------------- ------------- 6.6/9.9 MB 601.0 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 600.0 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 600.0 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 600.0 kB/s eta 0:00:06
   ---------------------------- ----------- 7.1/9.9 MB 595.9 kB/s eta 0:00:05
   ---------------------------- ----------- 7.1/9.9 MB 595.9 kB/s eta 0:00:05
   ----------------------------- ---------- 7.3/9.9 MB 598.4 kB/s eta 0:00:05
   ----------------------------- ---------- 7.3/9.9 MB 598.4 kB/s eta 0:00:05
   ------------------------------ --------- 7.6/9.9 MB 598.5 kB/s eta 0:00:04
   ------------------------------ --------- 7.6/9.9 MB 598.5 kB/s eta 0:00:04
   ------------------------------- -------- 7.9/9.9 MB 597.0 kB/s eta 0:00:04
   ------------------------------- -------- 7.9/9.9 MB 597.0 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 596.4 kB/s eta 0:00:03
   -------------------------------- ------- 8.1/9.9 MB 596.4 kB/s eta 0:00:03
   --------------------------------- ------ 8.4/9.9 MB 597.1 kB/s eta 0:00:03
   --------------------------------- ------ 8.4/9.9 MB 597.1 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/9.9 MB 596.5 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/9.9 MB 596.5 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.9 MB 595.3 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 595.3 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 594.2 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 594.2 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 593.7 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 593.7 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 593.9 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 593.9 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 590.6 kB/s  0:00:16
Downloading narwhals-2.16.0-py3-none-any.whl (443 kB)
Building wheels for collected packages: cufflinks
  Building wheel for cufflinks (setup.py): started
  Building wheel for cufflinks (setup.py): finished with status 'done'
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68792 sha256=0bbe04f100272c54d779c7a1af1c055966e8ed3c42e3d13758b7b80fc695c41b
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\09\8a\6b\cbe3e87b2e59bb5f90b49b034ce36b80b46a4d6e38444c34de
Successfully built cufflinks
Installing collected packages: colorlover, narwhals, plotly, cufflinks

   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   -------------------- ------------------- 2/4 [plotly]
   ------------------------------ --------- 3/4 [cufflinks]
   ---------------------------------------- 4/4 [cufflinks]

Successfully installed colorlover-0.3.0 cufflinks-0.17.3 narwhals-2.16.0 plotly-6.5.2

### Step 2: Enable interactive visualisations in Jupyter

In [6]:
!jupyter nbextension enable --py widgetsnbextension

usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: console dejavu events execute kernel kernelspec lab
labextension labhub migrate nbconvert notebook run script server troubleshoot
trust

Jupyter command `jupyter-nbextension` not found.

### Step 3: Import the required packages

In [10]:
# Standard data science helpers
import numpy as np
import pandas as pd
import scipy

# Instantiate the Plotly charting library.
import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly.express as px
# We use plotly.offline as this allows us to create interactive 
# visualisations without the use of an internet connection, 
# making our notebook more distributable to others. 
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

# The Cufflinks library allows us to directly bind 
# Pandas DataFrames to Plotly charts. 
import cufflinks as cf
# Once again, we use the Cufflinks library in offline mode. 
cf.go_offline(connected=True)
cf.set_config_file(colorscale='plotly', world_readable=True)

# Extra options. We use these to make our interactive 
# visualisations more aesthetically appealing. 
from IPython.core.display import HTML
pd.options.display.max_rows = 30
pd.options.display.max_columns = 25

# Show all code cells outputs.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

c:\ProgramData\anaconda3\envs\sqlenv\lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

### Step 4: Read in the data

For this project, we'll work with some stats data from `medium.com`.

In [11]:
df = pd.read_parquet('https://github.com/WillKoehrsen/Data-Analysis/blob/master/medium/data/medium_data_2019_01_26?raw=true')
df.head()

,claps,days_since_publication,fans,link,num_responses,publication,published_date,read_ratio,read_time,reads,started_date,tags,text,title,title_word_count,type,views,word_count,claps_per_word,editing_days,<tag>Education,<tag>Data Science,<tag>Towards Data Science,<tag>Machine Learning,<tag>Python
129,2,597.301123,2,https://medium.com/p/screw-the-environment-but...,0,None,2017-06-10 14:25:00+00:00,42.17,7,70,2017-06-10 14:24:00+00:00,"[Climate Change, Economics]","Screw the Environment, but Consider Your Walle...","Screw the Environment, but Consider Your Wallet",8,published,166,1859,0.001076,0,0,0,0,0,0
125,18,589.983168,3,https://medium.com/p/the-vanquishing-of-war-pl...,0,None,2017-06-17 22:02:00+00:00,30.34,14,54,2017-06-17 22:02:00+00:00,"[Climate Change, Humanity, Optimism, History]","The Vanquishing of War, Plague and Famine Part...","The Vanquishing of War, Plague and Famine",8,published,178,3891,0.004626,0,0,0,0,0,0
132,51,577.363292,20,https://medium.com/p/capstone-project-mercedes...,0,None,2017-06-30 12:55:00+00:00,20.02,42,222,2017-06-30 12:00:00+00:00,"[Machine Learning, Python, Udacity, Kaggle]",Capstone Project: Mercedes-Benz Greener Manufa...,Capstone Project: Mercedes-Benz Greener Manufa...,7,published,1109,12025,0.004241,0,0,0,0,1,1
126,0,576.520688,0,https://medium.com/p/home-of-the-scared-5af0fe...,0,None,2017-07-01 09:08:00+00:00,35.85,9,19,2017-06-30 18:21:00+00:00,"[Politics, Books, News, Media Criticism]",Home of the Scared A review of A Culture of Fe...,Home of the Scared,4,published,53,2533,0.000000,0,0,0,0,0,0
121,0,572.533035,0,https://medium.com/p/the-triumph-of-peace-f485...,0,None,2017-07-05 08:51:00+00:00,8.47,14,5,2017-07-03 20:18:00+00:00,"[Books, Psychology, History, Humanism]",The Triumph of Peace A review of The Better An...,The Triumph of Peace,4,published,59,3892,0.000000,1,0,0,0,0,0

Let's have a quick descriptive look at the data we've just pulled:

In [12]:
df.describe()

,claps,days_since_publication,fans,num_responses,read_ratio,read_time,reads,title_word_count,views,word_count,claps_per_word,editing_days,<tag>Education,<tag>Data Science,<tag>Towards Data Science,<tag>Machine Learning,<tag>Python
count,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000
mean,1815.263158,248.407273,352.052632,7.045113,29.074662,12.917293,6336.300752,7.127820,23404.030075,3029.120301,0.957638,20.330827,0.729323,0.609023,0.436090,0.383459,0.315789
std,2449.074661,179.370879,479.060117,9.056108,12.417670,9.510795,9007.284726,3.158475,33995.636496,2393.414456,1.846756,74.111579,0.445989,0.489814,0.497774,0.488067,0.466587
min,0.000000,1.218629,0.000000,0.000000,8.110000,1.000000,1.000000,2.000000,3.000000,163.000000,0.000000,-13.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,121.000000,74.543822,23.000000,0.000000,20.020000,8.000000,363.000000,5.000000,1375.000000,1653.000000,0.052115,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,815.000000,245.416130,136.000000,4.000000,27.060000,10.000000,2049.000000,7.000000,7608.000000,2456.000000,0.421525,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,2700.000000,376.080598,528.000000,12.000000,34.910000,14.000000,7815.000000,8.000000,30141.000000,3553.000000,1.099366,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,13600.000000,597.301123,2588.000000,59.000000,74.370000,54.000000,41978.000000,16.000000,173714.000000,15063.000000,17.891817,349.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Interactive visualisations
We'll now work through a few examples of interactive visualisations. We'll start with a simple filter to see how the interface works.

### Example 1

In [13]:
from ipywidgets import interact, interact_manual, widgets

To make a function interactive, we need to use the ```@interact``` decorator. 

But wait, what's a decorator? 

Simply put, a decorator is a Python function that wraps around another declared function to enhance or augment its behaviour, like putting a ribbon around a present to make it look prettier as a gift. We won't go into the semantics of how to _create_ a decorator, but you can easily spot them above a function with the form ``@decorator_name``. 
For more information, see: https://realpython.com/primer-on-python-decorators/

Consider the code below.

In [15]:
@interact
def show_articles_more_than(column='claps', x=5000):
    display(HTML(f'<h4>Showing articles with more than {x} {column}<h4>'))
    display(df.loc[df[column] > x, ['title', 'claps', 'published_date', 'read_time', 'tags', 'views', 'reads']])

interactive(children=(Text(value='claps', description='column'), IntSlider(value=5000, description='x', max=15…

The ```@interact``` decorator automatically inferred that we wanted a text box for the column and an interactive slider. This decorator makes it incredibly simple to add interactivity.

### Example 2

Now we will add a dropdown menu to select which column to filter on while simultaneously adding limits for x. 

A dropdown menu can be useful when we need to enforce constraints on the interaction.

In [16]:
@interact
def show_titles_more_than(x=(10, 50000, 10),
                          column=['read_time', 'views', 'reads']):
    display(HTML(f'<h4>Showing articles with more than {x} {column}<h4>'))
    display(df.loc[df[column] > x, ['title', 'published_date', 'read_time', 'tags', 'views', 'reads']])

interactive(children=(IntSlider(value=25000, description='x', max=50000, min=10, step=10), Dropdown(descriptio…

### Example 3

Moving on to more sophisticated data relationships that may be interactively represented, we construct a widget that quickly finds the correlation between two columns in the dataset.

In [18]:
@interact
def correlations(column1=list(df.select_dtypes('number').columns), 
                 column2=list(df.select_dtypes('number').columns)):
    print(f"Correlation: {df[column1].corr(df[column2])}")

interactive(children=(Dropdown(description='column1', options=('claps', 'days_since_publication', 'fans', 'num…

Within the above code example, we need to specify Pandas columns that are of a numeric type using the code `df.select_dtypes('number')` because the correlation statistic is only defined between numeric values.

### Example 4

We can use the same basic approach to create interactive widgets for plots. This approach allows us to expand the capabilities of the powerful `plotly` visualisation library.

In [19]:
@interact
def scatter_plot(x=list(df.select_dtypes('number').columns), 
                 y=list(df.select_dtypes('number').columns)[1:]):
    if x == y:
        print(f"Please select separate variables for X and Y")
    else:
        df.iplot(kind='scatter', x=x, y=y, mode='markers', 
                 xTitle=x.title(), yTitle=y.title(), title=f'{y.title()} vs {x.title()}')
        ## If you are using Google Colab, comment out the above line of code and uncomment the lines below
        #fig = px.scatter(df, x=x, y=y, title=f'{y.title()} vs {x.title()}')
        #fig.show(renderer="colab")

interactive(children=(Dropdown(description='x', options=('claps', 'days_since_publication', 'fans', 'num_respo…

### Example 5

In a similar fashion to the previous example, we can create a customisable heatmap of correlations:

In [20]:
cscales = ['Greys', 'YlGnBu', 'Greens', 'YlOrRd', 'Bluered', 'RdBu',
            'Reds', 'Blues', 'Picnic', 'Rainbow', 'Portland', 'Jet',
            'Hot', 'Blackbody', 'Earth', 'Electric', 'Viridis', 'Cividis']

# We use the Figure Factory module of Plotly, which
# defines many unique and powerful plots to be used
# in Python. 
# For more info, see: https://plot.ly/python/figure-factory-subplots/
import plotly.figure_factory as ff

corrs = df.corr(numeric_only=True)

@interact
def plot_corrs(colorscale=cscales):
    figure = ff.create_annotated_heatmap(z = corrs.round(2).values, 
                                     x =list(corrs.columns), 
                                     y=list(corrs.index), 
                                     colorscale=colorscale,
                                     annotation_text=corrs.round(2).values)
    iplot(figure)
    ## If you are using Google Colab, comment out the above line of code and uncomment the line below
    #figure.show(renderer="colab")

interactive(children=(Dropdown(description='colorscale', options=('Greys', 'YlGnBu', 'Greens', 'YlOrRd', 'Blue…

### Example 6

Interaction can also be extremely useful when we want to try and view various configurations for a plot that we are trying to produce. 

The following code allows us to add some options to control the colour scheme of a given Plotly chart. Here we call the `@interact_manual` decorator, which allows us to select multiple variables before our chart is updated.

In [21]:
@interact_manual
def scatter_plot(x=list(df.select_dtypes('number').columns), 
                 y=list(df.select_dtypes('number').columns)[1:],
                 theme=list(cf.themes.THEMES.keys()), 
                 colorscale=list(cf.colors._scales_names.keys())):
    
    if x == y:
        print(f"Please select separate variables for X and Y")
    else:
        df.iplot(kind='scatter', x=x, y=y, mode='markers', 
                 xTitle=x.title(), yTitle=y.title(), 
                 text='title',
                 title=f'{y.title()} vs {x.title()}',
                theme=theme, colorscale=colorscale)
        ## If you are using Google Colab, comment out the above line of code and uncomment the line below
        #fig = px.scatter(df, x=x, y=y, title=f'{y.title()} vs {x.title()}')
        #fig.show(renderer="colab")

interactive(children=(Dropdown(description='x', options=('claps', 'days_since_publication', 'fans', 'num_respo…

### Example 7

The decorator ```@interact``` is not the only way to use widgets. 

Read through the following example to figure out how else we can use widgets.

In [22]:
df.set_index('published_date', inplace=True)

In [23]:
def print_articles_published(start_date, end_date):
    start_date = pd.Timestamp(start_date)
    end_date = pd.Timestamp(end_date)
    stat_df = df.loc[(df.index >= start_date) & (df.index <= end_date)].copy()
    total_words = stat_df['word_count'].sum()
    total_read_time = stat_df['read_time'].sum()
    num_articles = len(stat_df)
    print(f'According to our dataset, published by Medium.com, there are {num_articles} articles between {start_date.date()} and {end_date.date()}.')
    print(f'These articles totalled {total_words:,} words and {total_read_time/60:.2f} hours to read.')
    
_ = interact(print_articles_published,
             start_date=widgets.DatePicker(value=pd.to_datetime('2018-01-01')),
             end_date=widgets.DatePicker(value=pd.to_datetime('2019-01-01')))

interactive(children=(DatePicker(value=Timestamp('2018-01-01 00:00:00'), description='start_date', step=1), Da…

### Example 8

For our final example, we use the `Dropdown` and `DatePicker` widgets to plot one column cumulatively up to a certain time.

In [24]:
def plot_up_to(column, date):
    date = pd.Timestamp(date)
    plot_df = df.loc[df.index <= date].copy()
    plot_df[column].cumsum().iplot(mode='markers+lines', 
                                   xTitle='published date',
                                   yTitle=column, 
                                  title=f'Cumulative {column.title()} Until {date.date()}')
    
_ = interact(plot_up_to, column=widgets.Dropdown(options=list(df.select_dtypes('number').columns)), 
             date = widgets.DatePicker(value=pd.to_datetime('2019-01-01')))

interactive(children=(Dropdown(description='column', options=('claps', 'days_since_publication', 'fans', 'num_…

## Summary

Jupyter Notebook is a great data exploration and analysis environment. Using tools like notebook extensions and interactive widgets makes our job as data-driven storytellers even more efficient. Widgets are powerful tools that allow us to make our data more interactive and, therefore, more accessible to non-data scientists.

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:140px";/>
</div>